# This file is auto-generated by endara-ai/endara-desktop's release workflow.
# Manual edits will be overwritten on the next release.
cask "endara" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.4"
  sha256 arm:   "8abe7b70abf50e2ec436afd9e212b3c0e126a59b595e91da42ceede2b3d62cef",
         intel: "df4044eb0aac76a28ce7e0e63a9d4f961b06455752afcd394453169010c6fdb6"

  url "https://github.com/endara-ai/endara-desktop/releases/download/v#{version}/Endara.Desktop_#{version}_#{arch}.dmg"
  name "Endara"
  desc "Desktop app for managing the Endara MCP server aggregator"
  homepage "https://github.com/endara-ai/endara-desktop"

  auto_updates true
  depends_on macos: ">= :catalina"

  app "Endara Desktop.app"

  zap trash: [
    "~/Library/Application Support/ai.endara.desktop",
    "~/Library/Caches/ai.endara.desktop",
    "~/Library/HTTPStorages/ai.endara.desktop",
    "~/Library/Logs/Endara Desktop",
    "~/Library/Preferences/ai.endara.desktop.plist",
    "~/Library/Saved Application State/ai.endara.desktop.savedState",
    "~/Library/WebKit/ai.endara.desktop",
  ]
end
