# This file is auto-generated by endara-ai/endara-desktop's release workflow.
# Manual edits will be overwritten on the next release.
cask "endara" do
  version "0.1.8"
  sha256 "0707cf47fda1522f1797faee251944d8d23c2a8c5ebfdb097c80a3a7125997fe"

  url "https://github.com/endara-ai/endara-desktop/releases/download/v#{version}/Endara.Desktop_#{version}_aarch64.dmg"
  name "Endara"
  desc "Desktop app for managing the Endara MCP server aggregator"
  homepage "https://github.com/endara-ai/endara-desktop"

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: ">= :catalina"

  app "Endara Desktop.app"

  zap trash: [
    "~/Library/Application Support/ai.endara.desktop",
    "~/Library/Caches/ai.endara.desktop",
    "~/Library/HTTPStorages/ai.endara.desktop",
    "~/Library/Logs/Endara Desktop",
    "~/Library/Preferences/ai.endara.desktop.plist",
    "~/Library/Saved Application State/ai.endara.desktop.savedState",
    "~/Library/WebKit/ai.endara.desktop",
  ]
end
