# This file is auto-generated by endara-ai/endara-desktop's release workflow.
# Manual edits will be overwritten on the next release.
cask "endara" do
  arch arm: "aarch64", intel: "x64"

  version "0.1.5"
  sha256 arm:   "0d28aa36ff07be4749e1b402244cd5858ed31f3dca9e5245c0c3ed70fa7016b9",
         intel: "0e3a496a11f0fb30aed054386f28c741f9e5d64174ff4f5b1e19f3996b6d7bbd"

  url "https://github.com/endara-ai/endara-desktop/releases/download/v#{version}/Endara.Desktop_#{version}_#{arch}.dmg"
  name "Endara"
  desc "Desktop app for managing the Endara MCP server aggregator"
  homepage "https://github.com/endara-ai/endara-desktop"

  auto_updates true
  depends_on macos: ">= :catalina"

  app "Endara Desktop.app"

  zap trash: [
    "~/Library/Application Support/ai.endara.desktop",
    "~/Library/Caches/ai.endara.desktop",
    "~/Library/HTTPStorages/ai.endara.desktop",
    "~/Library/Logs/Endara Desktop",
    "~/Library/Preferences/ai.endara.desktop.plist",
    "~/Library/Saved Application State/ai.endara.desktop.savedState",
    "~/Library/WebKit/ai.endara.desktop",
  ]
end
