# This file is auto-generated by endara-ai/endara-relay's release workflow.
# Manual edits will be overwritten on the next release.
class EndaraRelay < Formula
  desc "Local MCP tool aggregator — one endpoint for many MCP servers"
  homepage "https://github.com/endara-ai/endara-relay"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "1fbf4ef752d38bd8adfa87822fb564980acf380b00af66a54d22d6ebdfc4024a"
    end
    on_intel do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "597de8fa0db81ea04a4c2dec551e4f82eda242c7e78ac97b417e7932c2540195"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e589a9ceb2e0f4a4133fa9175d0b7d7f4e04844817fbcd9874afe01877c62fe3"
    end
    on_intel do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "adf76037333cd90513dc9e66ffcb832376866f10e44c1bf2072849f156c7e0b4"
    end
  end

  def install
    bin.install "endara-relay"
  end

  test do
    assert_match "endara-relay", shell_output("#{bin}/endara-relay --version")
  end
end
