# This file is auto-generated by endara-ai/endara-relay's release workflow.
# Manual edits will be overwritten on the next release.
class EndaraRelay < Formula
  desc "Local MCP tool aggregator — one endpoint for many MCP servers"
  homepage "https://github.com/endara-ai/endara-relay"
  version "0.1.7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "7319ecae507f41488565451b8b708d0002d8f09653c4d2f956000ae9c7f968a6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8fc630421baaceebcfe85d7a168514271fc42a2d38de017591631e4b5e9e2452"
    end
    on_intel do
      url "https://github.com/endara-ai/endara-relay/releases/download/v#{version}/endara-relay-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "af1d0d18d7cf94b0e4c0a0d41d42fd69b48cbb1b2ea418e7ea71b1fa8b768717"
    end
  end

  def install
    bin.install "endara-relay"
  end

  test do
    assert_match "endara-relay", shell_output("#{bin}/endara-relay --version")
  end
end
